services:
  db:
    image: postgres:15
    platform: linux/arm64
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: market_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    platform: linux/arm64
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:
